### ISSUE TITLE
AppVeyor build

### ISSUE THREAD

**Issue by stevehansen** [stevehansen/classify-data#5]

**Comment by Atrejoe** [comment]
Hi Steve,

This is very straightforward:

1. Create an AppVeyor account.
2. If you authenticated using your GitHub credentials, you can simply create a new 'project' and select this repository.
3. Enable (NuGet) package restore:
![image](https://user-images.githubusercontent.com/585091/40723994-50dae99a-6420-11e8-8fdc-158ac9bcd32f.png)
4. There is one gotcha for this particular project: in order to be able to use the newer syntax, user build worker image `Visual Studio 2017` (or higher)
![image](https://user-images.githubusercontent.com/585091/40723946-3a03397a-6420-11e8-9213-30c035854d02.png)
